FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:latest-build as build

WORKDIR /app
COPY src/ .

ENV GOOS=linux CGO_ENABLED=0
RUN go get -d -v && \
    go build -o credential-uploader

FROM scratch as run
COPY --from=build /app/credential-uploader /

ENTRYPOINT [ "/credential-uploader" ]
